### ISSUE TITLE
NVIC_GetPendingIRQ(...) must be with assert_param(...)

### ISSUE THREAD

**Issue by vitkorob** [eldarkg/emdr1986x-std-per-lib#12]
I try to use the `NVIC_GetPendingIRQ(SysTick_IRQn)`, but `SysTick_IRQn` is not correct argument for this function!

This function and other similar must check the input arguments.

I will make implementation and a pull request.

**Comment by eldarkg** [comment]
@vitkorob what status of your suggestion?

**Comment by eldarkg** [comment]
@vitkorob Can you to answer?

**Comment by eldarkg** [comment]
@vitkorob Is it actual yet?

**Comment by vitkorob** [comment]
Hello,

Sorry for delay. This issue isn't actual, because code of this function is a [part of official code](//github.com/ARM-software/CMSIS/blob/master/CMSIS/Include/core_cm3.h). The assert_param expression is a part of manufacturer peripheral driver code and expression is not applicable.
