### ISSUE TITLE
EEPROM_ReadWord возвращает 0 при сборке MDR32F9Qx_eeprom.c с -O2

### ISSUE THREAD

**Issue by legath** [eldarkg/emdr1986x-std-per-lib#25]
EEPROM_ReadWord всегда возвращает 0 , даже если данные есть. Настройки задержек верные т.к. с оптимизацией 0 все работает.

**Comment by eldarkg** [comment]
@legath Могли бы вы приложить скомпилированный объектный файл с отладочными символами (флаг -ggdb3)?

**Comment by legath** [comment]
gcc version 5.4.1 20160919
[eeprom.zip](https://github.com/eldarkg/emdr1986x-std-per-lib/files/1152073/eeprom.zip)

**Comment by eldarkg** [comment]
@legath Извините, хотелось бы увидеть скомпилированный объектный файл с отладочными символами самой программы (т.е. после линковки).

**Comment by eldarkg** [comment]
@legath Судя по версии GCC: (15:5.4.1+svn241155-1) 5.4.1 20160919 (взято из объектного файла), вы используете среду компилятора из дебиановского (убунтовского) репозитория.
Я бы вам по рекомендовал использовать компилятор [от сюда](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm). Это официальная сборка, поддерживаемая ARM. 
Насколько я помню у меня были когда-то проблемы с запуском программы скомпилированной компилятор из стандартного (убунту) репо.

**Comment by eldarkg** [comment]
@legath И для уточнения, вы используете последнюю версию данной библиотеки?

**Comment by legath** [comment]
@eldarkg да, я делал pull к себе. 
Для уточнения, я нашел что на **новом** контроллере перед работой с EEPROM необходимо вызывать EEPROM_ErasePage, тогда при последующей работе все читается и пишется не зависимо о количества циклов подачи питания. 

Компилятор у меня не из репозитория , а с лаунчпад, но сути это не меняет. Воспользуюсь Вашим советом и протестирую на рекомендованном. Спасибо.

**Comment by eldarkg** [comment]
@legath По сути в принципе надо перед тем чем что-то записать в ЕЕПРОМ необходимо делать очистку страницы (для сведения: очистка - заполнение памяти единицами; запись - только сброс битов в 0. Т.е. если бит, который вы хотите установить в единицу уже нулевой, его можно взвести только полным стиранием страницы, с последующей записью необходимых данных).
Я не стал бы надеяться на производителя, что он стерет эту память.

**Comment by eldarkg** [comment]
@legath Можно закрывать вопрос?

**Comment by legath** [comment]
Думаю что можно закрывать. 
Хотя момент с чтением 0 все равно не совсем понятен, особенно после Вашего комментария.

**Comment by eldarkg** [comment]
@legath Т.е. я  имею ввиду, что если в памяти уже нули, после записи туда каких-либо данных, там так и будут нули.
