### ISSUE TITLE
MDR1986VE1T.h - unterminated extern "C" {

### ISSUE THREAD

**Issue by alex-khoroshko** [eldarkg/emdr1986x-std-per-lib#28]
There's a check at the top of file:
```
#ifdef __cplusplus
extern "C" {
#endif
```
but there is no corresponding closing part. If compiled with g++ as c++, header spoils everything below to compile with C linkage and compiler gives "error: expected '}' at end of input"

**Comment by eldarkg** [comment]
@alex-khoroshko Thank you
