### ISSUE TITLE
Unnecessary include for non-Keil compilers in MDR32F9Qx_config.h

### ISSUE THREAD

**Issue by Amomum** [eldarkg/emdr1986x-std-per-lib#32]
There is an include of the MDR32F9Qx_board.h, which is not present in this repo and, I think, is totally unnecessary:

```
#if ((__CC_ARM == 0) || (__ARMCC_VERSION < 5000000))
	#include "MDR32F9Qx_board.h"
#endif
```

I guess it's legacy from the demo project.

**Comment by eldarkg** [comment]
@Amomum Look at issue #6
