### ISSUE TITLE
Mixed tabs and spaces in multiple files

### ISSUE THREAD

**Issue by Amomum** [eldarkg/emdr1986x-std-per-lib#34]
For example, MDR32F9Qx_uart.h uses spaces only, MDR32F9Qx_adciu.h uses tabs only, MDR32F9Qx_adc.h uses both.

It's not big deal but it is unpleasant and inconsistent. I don't even know what is the _correct_ policy for this repo since so many files are different.

I believe we should pick tabs or spaces and make it consistent.

**Comment by eldarkg** [comment]
@Amomum Yes, I saw that issue. But this repo periodically (rare) merged with official one and changing formating of code will lead to problems of merge.
