### ISSUE TITLE
В документации на 1986ВЕ1Т структура регистров ядра отличается от файла MDR1986VE1T.h

### ISSUE THREAD

**Issue by RegisterWindowClassEx** [eldarkg/emdr1986x-std-per-lib#5]
Доброго времени суток!
В файле структура описана следующим образом: 
typedef struct {
	__IO uint32_t CPUID;		//5
	__IO uint32_t ICSR;		//6
	__IO uint32_t Reserved3;		//0
	__IO uint32_t AIRCR;		//7
	__IO uint32_t Reserved4;		//0
	__IO uint32_t CCR;		//8
	__IO uint32_t SHP2;		//9
	__IO uint32_t SHP3;		//10
	__IO uint32_t SHCSR;		//11	
} MDR_ECB_TypeDef;

Судя по спецификации между CCR и SHP2 должен быть ещё один зарезервированный регистр, т.к. смещения этих регистров отличаются на 8, а не на 4.

**Comment by eldarkg** [comment]
Не знаю откуда вы черпаете свой код, но в данной библиотеке используется следующая структура (из файла [core_cm1.h](https://github.com/eldarkg/emdr1986x-std-per-lib/blob/master/CMSIS/CM1/CoreSupport/core_cm1.h#L308)) и вроде в ней всё верно:
```C
typedef struct
{
  __I  uint32_t CPUID;                   /*!< Offset: 0x000 (R/ )  CPUID Base Register                                   */
  __IO uint32_t ICSR;                    /*!< Offset: 0x004 (R/W)  Interrupt Control and State Register                  */
       uint32_t RESERVED0;
  __IO uint32_t AIRCR;                   /*!< Offset: 0x00C (R/W)  Application Interrupt and Reset Control Register      */
  __IO uint32_t SCR;                     /*!< Offset: 0x010 (R/W)  System Control Register                               */
  __IO uint32_t CCR;                     /*!< Offset: 0x014 (R/W)  Configuration Control Register                        */
       uint32_t RESERVED1;
  __IO uint32_t SHP[2];                  /*!< Offset: 0x01C (R/W)  System Handlers Priority Registers. [0] is RESERVED   */
  __IO uint32_t SHCSR;                   /*!< Offset: 0x024 (R/W)  System Handler Control and State Register             */
} SCB_Type;
```
Структура MDR_ECB_TypeDef отсутствует в данной библиотеке. В следующий раз прежде чем сообщать об ошибке убедитесь о ее наличии в ней.
