### ISSUE TITLE
CAN - (uint32_t) в макросах ломает препроцессор

### ISSUE THREAD

**Issue by alexrayne** [eldarkg/emdr1986x-std-per-lib#52]
Привет!
в макросах SPL MDR32F9Qx по делу и без вставляется приведение к типу (uint32_t). в результате такая константа не может обрабатываться препроцессором в директивах `#if`
пример:
MDR32F9Qx_can.h:379: 
#define CAN_BUFFER_NUMBER           ((uint32_t)32)

макро CAN_BUFFER_NUMBER невозможно использовать в:
`#if ( CAN_CONNECTIONS_LIMIT > (CAN_BUFFER_NUMBER /2) )`

**Comment by eldarkg** [comment]
@alexrayne Привет.
Попробуйте до макроса `#if` указать следующее:
```C
#include <stdint.h>
```

**Comment by alexrayne** [comment]
Эльдар, препроцессор не понимает типов С вообще.
у вас это работает? на каком компиляторе?

**Comment by eldarkg** [comment]
@alexrayne Извиняюсь. Исправил
