### ISSUE TITLE
Обозначения векторов прерываний в разных startup-файлах не соответствуют друг другу

### ISSUE THREAD

**Issue by andshn** [eldarkg/emdr1986x-std-per-lib#56]
Пример
https://github.com/eldarkg/emdr1986x-std-per-lib/blob/b3f25b34892cc4a95cb445a63e3c3b7cdd044918/CMSIS/CM1/DeviceSupport/MDR1986VE1T/startup/gcc/startup_MDR1986VE1T.S#L104
https://github.com/eldarkg/emdr1986x-std-per-lib/blob/b3f25b34892cc4a95cb445a63e3c3b7cdd044918/CMSIS/CM1/DeviceSupport/MDR1986VE1T/startup/arm/startup_MDR1986VE1T.s#L70
Отличаются регистры символов, т.е. в одном случае написано прописными буквами, в другом строчными. Может быть стоит привести все в соответствие с официальной библиотекой?

**Comment by eldarkg** [comment]
@andshn Thank u
