### ISSUE TITLE
Ошибки, произошедшие в результате слияния с Software pack 1986ВЕ8(1)Т

### ISSUE THREAD

**Issue by andshn** [eldarkg/emdr1986x-std-per-lib#57]
Из-за этого MDR32F9Qx_eth.c даже не компилируется.
https://github.com/eldarkg/emdr1986x-std-per-lib/blob/b3f25b34892cc4a95cb445a63e3c3b7cdd044918/MDR32F9Qx_StdPeriph_Driver/src/MDR32F9Qx_eth.c#L247
https://github.com/eldarkg/emdr1986x-std-per-lib/blob/b3f25b34892cc4a95cb445a63e3c3b7cdd044918/CMSIS/CM1/DeviceSupport/MDR1986VE1T/inc/MDR1986VE1T.h#L4136
В официальной библиотеке ETH_Dilimiter. Возможно стоит проверить, не привело ли это слияние к другим ошибкам.

**Comment by eldarkg** [comment]
@andshn Thank u
