### ISSUE TITLE
IAR preprocessor error and a nonexistent file

### ISSUE THREAD

**Issue by vitkorob** [eldarkg/emdr1986x-std-per-lib#6]
There is code in the file [MDR32F9Qx_config.h](../blob/master/Config/MDR32F9Qx_config.h):

```
#if ((__CC_ARM == 0) || (__ARMCC_VERSION < 5000000))
    #include "MDR32F9Qx_board.h"
#endif
```

I think should remove or somehow modify this code. My reasons below.
- File _MDR32F9Qx_board.h_ didn't exist in repo.
- Macro __CC_ARM never equal _0_ in a normal use. Always set to 1 for the ARM compiler or _0_ for other. See [predefined macros for the ARM compiler](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0282b/Babbacdb.html) and [C99 standard specifies](http://stackoverflow.com/questions/5085392/what-is-the-value-of-an-undefined-constant-used-in-if-c).

I'm using IAR and I have an annoying problem with this code. What is your opinion?

**Comment by eldarkg** [comment]
@vitkorob Hello.
I don't usage this lines too. Maybe delete the redundant code?

**Comment by eldarkg** [comment]
@vitkorob I don't sure about correct checking of predefined macros

**Comment by eldarkg** [comment]
@vitkorob This is used in [examples in doc repo](https://github.com/eldarkg/emdr1986x-std-per-lib-doc/tree/master/Examples).
